### ISSUE TITLE
Enable setInvalidatedByBiometricEnrollment

### ISSUE THREAD

**Issue by EdinsonNM** [authpass/biometric_storage#11]
Hello, I have a question,  it is possible to enable setInvalidatedByBiometricEnrollment?

 I need to use setInvalidatedByBiometricEnrollment(true) while generating key and the key gets invalidated on any new biometric enrollment. An exception is thrown when you try to use the same key. In this situation, you can reset the biometric app settings inside your app and start the process of enabling biometrics again.

**Comment by hpoul** [comment]
Hi,
I'm not quite sure what you are referring to. By default `setInvalidatedByBiometricEnrollment` [is enabled](https://developer.android.com/reference/android/security/keystore/KeyGenParameterSpec.Builder#setInvalidatedByBiometricEnrollment(boolean)), and as far as I can see we don't disable it anywhere.

**Comment by EdinsonNM** [comment]
How to disable the keyvalue if the user add new fingerprint to Android settings after he/she authenticate finger inside my application ?

**Comment by hpoul** [comment]
@EdinsonNM as I said, imho this is **the default behavior**. Are you sure that this is not already the case?

**Comment by EdinsonNM** [comment]
I was reviewing your code apparently the way you perform the encryption is not taking into account when changes occur in the biometric.
I'm writing my own library and this one is working.  I am not an Android expert but I managed to encrypt in a different way than you do and it worked.

I'm sorry, my English is really bad :(

**Comment by EdinsonNM** [comment]
you can try writing a value, then try adding a fingerprint and then try reading that value.  this value must be permanently invalidated

**Comment by hpoul** [comment]
I think I now found the problem. the API documentation https://developer.android.com/reference/android/security/keystore/KeyGenParameterSpec.Builder#setInvalidatedByBiometricEnrollment(boolean) reads:

> Sets whether this key should be invalidated on biometric enrollment. This applies only to keys which require user authentication (see setUserAuthenticationRequired(boolean)) and if no positive validity duration has been set (see setUserAuthenticationValidityDurationSeconds(int), meaning the key is valid for biometric authentication only.
>
> By default, invalidateKey is true

Now, what i **thought** this meant is, that `invalidateKey` is true, and it can be turned off when `setUserAuthenticationRequired` = true and `setUserAuthenticationValidityDurationSeconds` <= 0 -- but now I guess that it actually means this option all does not apply at all when either `setUserAuthenticationRequired` is not true, or `setUserAuthenticationValidityDurationSeconds` is > 0, because then the key is never invalidated? at least that seems to be the behavior.

And it is not possible to use `setUserAuthenticationValidityDurationSeconds` to 0 because androidx.security won't let you: https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-master-dev/security/crypto/src/main/java/androidx/security/crypto/MasterKeys.java?source=post_page---------------------------%2F&autodive=0%2F%2F%2F%2F%2F#126

<img width="713" alt="Screen Shot 2020-09-18 at 01 19 50" src="https://user-images.githubusercontent.com/313066/93537913-13e82380-f94d-11ea-9387-0e0ac4ca36d3.png">

Not sure how this can be workarounded from my end..

**Comment by loposkin** [comment]
Are there any security concerns to use `SecretKey` instead of `MasterKey` to encrypt the data? It is also mentioned in [this article](https://developer.android.com/training/sign-in/biometric-auth#declare-supported-authentication-types) on biometric authentication from android documentation

**Comment by hpoul** [comment]
@loposkin the `SecretKey` in that article has nothing to do with the `MasterKey` used by this plugin.. these are just classes of different libraries for different abstractions, and are have nothing to do with the actual encryption being used.. also i'm not sure what these has to do with `invalidatedByBiometricEnrollment`... 

fwiw, i'll close this issue, has [detailed in my last comment](https://github.com/authpass/biometric_storage/issues/11#issuecomment-694551105) i don't think `setInvalidatedByBiometricEnrollment` is applicable when using `EncryptedFile` from `androidx.security`.
